### ISSUE TITLE
Selected filters are not displayed at pages 2+ after reloading the page if FSE

### ISSUE THREAD

**Issue by gfarma** [superspeedyplugins/issue-tracker#10] opened 2023-11-24 12:23 UTC
**Describe the bug**
When you select a fitler, change the page and hit reload it is not selected.
This happens at FSE themes.
(active filters are displayed correctly after the page reload)

**To Reproduce**
You can replicate with these steps:
https://fshome-19344.ove-ams.servebolt.cloud/category/all-categories/pomola/pomola-portas/pomola-portas-me-rozeta/

select 
![image](https://github.com/superspeedyplugins/issue-tracker/assets/112942896/cfc06a50-5c77-43f3-921e-d122342e3e57)

1) select a filter (that has a lot of products to display more than 1 page)
2) go at page 2 or 3 etc
3) reload the page
4) the selected filter is not selected with its checkbox

**Comment by gfarma** [comment] 2023-11-25 13:41
If you test the link above at smaller displays (tablet/mobile) the same happens inside the panel, even at the page 1

**Comment by dhilditch** [comment] 2023-12-14 19:42
This is an issue on all themes, not just FSE's.

Please replicate in your local environment:

1. Load woo sample products
2. Add enough products to 1 category to create pagination or set products per page to 4
3. Add a SSF filter for product and product_category
4. Select the filter from the front-end
5. Select page 2

Confirm that the selected category is no longer selected.

To fix this, the selection of active filters happens through JavaScript. Each category URL has a 'canonical' data attribute which tells you what the URL is with this filter active.

The code already exists in JS to check for this - the issue is that we need some kind of wildcard to ignore /page/X/ from the URL. You can find the relevant code in super-speedy-filters.js

**Comment by gfarma** [comment] 2023-12-27 13:03
I tried the above steps.

I have the exact same set up (double checked it), at live and staging.
But at live is not working.

Live:
https://fshome.gr/category/all-categories/pomola/pomola-epiplon/labes-epiplon/page/5/?pa_apostasi-tripimatos=281%2C293&expand_pa_apostasi-tripimatos=1

Staging:
https://fshome-19344.ove-ams.servebolt.cloud/category/all-categories/pomola/pomola-epiplon/labes-epiplon/page/5/?pa_apostasi-tripimatos=281%2C293&expand_pa_apostasi-tripimatos=1


One difference is that at the live I have a lot more filters compared to staging.

**Comment by gfarma** [comment] 2024-01-11 10:11
Thanks for 5.16 update, it works nice with the filters.

One issue that still exists is that the same happens when sorting is been applied and you change page.

**Comment by dhilditch** [comment] 2024-01-18 10:17
Evgen, the code you made to fix the 'show selected filters' on pagination is working but a very similar issue exists when users sort their results. Can you create a branch for this weeks edits and update the code you made to also ignore ?orderby and &orderby

**Comment by dhilditch** [comment] 2024-02-08 12:00
Fixed in 5.17

**Closed by dhilditch** 2024-02-08 12:01 UTC
Labels: approved, Super Speedy Filters
